### ISSUE TITLE
prefer standard `rake db:*` commands to rake db:nuke_pave

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/rails-api-library-demo#2]
More useful from a pedagogical perspective.

Perhaps also warn on the implications of destroy/create versus additive changes.

**Comment by raq929** [comment]
What are the standard commands you'd like to use?

**Comment by raq929** [comment]
Nevermind, it seems like this issue has been resolved.

**Comment by raq929** [comment]
I'm updating to `rake db:drop db:create db:migrate`
