### ISSUE TITLE
Include instructions after clone

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/rails-api-library-demo#6]
After fork/clone `git checkout --track origin/training/single` to create and track the single branch on dev's local.

**Comment by gaand** [comment]
Why not just `git checkout training/single`?

**Comment by payne-chris-r** [comment]
If it all builds on itself, why not just `training`? Or is the idea that `training/one-to-many` branches off of `training/single`?

**Comment by jrhorn424** [comment]
Closing for now, this isn't necessary in the way the sequence is being delivered this time.
