### ISSUE TITLE
When updating from origin

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/rails-api-library-demo#7]
Include instructions:

`git fetch --all`

`git branch solution/one-to-many origin/solution/one-to-many`
[`git branch <branch_name> <remote>/<branch_to_checkout>`]

Push to origin with `git push -u <git_ssh_of_forked>`

**Comment by payne-chris-r** [comment]
Why is this here @J-Weeks ?

**Comment by jrhorn424** [comment]
Shouldn't be needed.

**Comment by jrhorn424** [comment]
Closed due to insufficient activity and context.
